name: AWS OIDC Connect
on:
  push:
    branches: [ main ]

jobs:
  ConnectToAWS:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required to request the OIDC JWT token
      contents: read    # Required to read the repository code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::884128492921:role/BankAppOIDC
          aws-region: us-east-1
